providers:
  compute:
    clouds:
      - rackspace
      - dimensiondata
  backup:
    clouds:
      - dimensiondata
configuration:
  disable_certificate_validation: true
  compute:
    dimensiondata:
      api_key: "bob"
      api_secret: "blah"